#!/usr/bin/python2
'''
Copyright (c) 2013, Patrick Louis <patrick at unixhub.net>

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    1.  The author is informed of the use of his/her code. The author does not have to consent to the use; however he/she must be informed.
    2.  If the author wishes to know when his/her code is being used, it the duty of the author to provide a current email address at the top of his/her code, above or included in the copyright statement.
    3.  The author can opt out of being contacted, by not providing a form of contact in the copyright statement.
    4.  If any portion of the author's code is used, credit must be given.
            a. For example, if the author's code is being modified and/or redistributed in the form of a closed-source binary program, then the end user must still be made somehow aware that the author's work has contributed to that program.
            b. If the code is being modified and/or redistributed in the form of code to be compiled, then the author's name in the copyright statement is sufficient.
    5.  The following copyright statement must be included at the beginning of the code, regardless of binary form or source code form.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Usage: hub filename
for STDIN: cat somefile| hub -stdin
'''
import mechanize,re,sys,os

HEADER = '\033[95m'
OKBLUE = '\033[94m'
OKGREEN = '\033[92m'
WARNING = '\033[93m'
FAIL = '\033[91m'
ENDC = '\033[0m'

INFO  = HEADER+"["+OKBLUE+"*"+HEADER+"] "+ENDC
ARROW = " "+OKGREEN+">> "+ENDC
PLUS  = HEADER+"["+OKGREEN+"+"+HEADER+"] "+ENDC
MINUS = HEADER+"["+FAIL+"-"+HEADER+"] "+ENDC

class hub_uploader(object):
    def __init__(self,filename,text_or_not=False):
        self.user        = ""
        self.passwd      = ""
        self.filename    = filename
        self.text_or_not = text_or_not

    def create_br(self):
        br = mechanize.Browser()
        br.set_handle_robots(False)
        return br

    def uploading(self,br):
        if self.text_or_not:
            br.select_form(nr=0)
            br.form['content'] = self.filename
        else:
            br.select_form(nr=1)
            br.form.add_file(open(self.filename), 'application/octet-stream', self.filename)
        print INFO+"Uploading"
        br.submit()
        if not self.text_or_not:
            print PLUS + "Finished uploading "+self.filename 
        return br

    def login_in(self,br):
        br.open("http://paste.unixhub.net/index.php/user/login","username="+self.user+"&password="+self.passwd+"&process=Login")
        return br

    def getting_link(self,br):
        try:
            print re.findall("};\n\t\twindow.paste_base = \'([^<>]*)';\n\t\t",br.response().read())[0]
        except:
            print re.findall("e:</p>\n\t<p>\n\t\t\t<a href=\"([^>]*)\">http://paste.uni",br.response().read())[0]
    
    def readconfigs(self):
        try:
            o = open(os.getenv("HOME") +"/.netrc",'r').readlines()
            for o_ in o:
                if "paste.unixhub.net" in o_:
                    o_ = o_.split(" ")
                    self.user   = o_[3].rstrip()
                    self.passwd = o_[5].rstrip()
        except:
            print MINUS+"There's nothing in the .netrc related to unixhub"

    def procedure(self):
        self.readconfigs()
        br = self.create_br()
        br = self.login_in(br)
        br = self.uploading(br)
        self.getting_link(br)

def main():
    sys.argv.reverse()
    sys.argv.pop()
    try:
        tester = sys.argv[0]
        if tester == '-stdin' or tester == '-s' or tester == 's' :
            a = ""
            for line in sys.stdin:
                a += line
            HUB = hub_uploader(a,True)
            HUB.procedure()
        else:
            for arg in sys.argv:
                HUB = hub_uploader(arg)
                HUB.procedure()
            print INFO+"END"
    except:
        print MINUS + "Usage: hub file or cat file|hub -stdin"

if __name__ =='__main__':
    main()
